name: Deploy to Server

on:
  push:
    branches:
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          mkdir -p /root/healworld_uat/Healworld_backend_main
          cd /root/healworld_uat/Healworld_backend_main
          git fetch origin
          git reset --hard origin/uat
          yarn install
          docker build -t healworld-main-backend-uat:all -f Dockerfile-uat --no-cache
          docker compose -f docker-compose-uat.yml up -d --build
          docker system prune -f
