name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          mkdir -p /root/healworld/Healworld_backend_main
          cd /root/healworld/Healworld_backend_main
          git fetch origin
          git reset --hard origin/main
          yarn install
          docker build -t healworld-main-backend:all -f Dockerfile-hw . --no-cache
          docker compose -f docker-compose-hw.yml up -d --build
          mkdir -p /root/nightlife/Healworld_backend_main
          cd /root/nightlife/Healworld_backend_main
          git fetch origin
          git checkout main
          git reset --hard origin/main
          yarn install
          docker build -t nightlife-main-backend:all -f Dockerfile-nl . --no-cache
          docker compose -f docker-compose-nl.yml up -d --build
          docker system prune -f
