name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          eval "$(ssh-agent -s)"  # เริ่ม SSH Agent
          export SSH_AUTH_SOCK=$(ls /tmp/ssh-*/agent.* 2>/dev/null | head -n 1)
          ssh-add ~/.ssh/id_rsa_git_hiddengem1 || true

          mkdir -p /root/hiddengem/hiddengem_backend_1
          cd /root/hiddengem/hiddengem_backend_1
          git remote -v  # ตรวจสอบว่าใช้ SSH หรือ HTTPS
          git fetch origin
          git reset --hard origin/main
          yarn install
          docker build -t healworld-main-backend:all -f Dockerfile-hw . --no-cache
          docker compose -f docker-compose-hw.yml up -d --build
          docker build -t nightlife-main-backend:all -f Dockerfile-nl . --no-cache
          docker compose -f docker-compose-nl.yml up -d --build
          docker system prune -f
